### ISSUE TITLE
Демо-страница

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/FSD-Task-4-v3#1]
Должна быть выполнена по типу второго задания, с разбиением на блоки и использованием препроцессоров pug и scss.
Демо-страница - это пример того, как плагин может быть использован потенциальными пользователями

**Comment by Everrest1** [comment]
Разные классы у элемента

![image](https://user-images.githubusercontent.com/43137324/122872601-5a820880-d339-11eb-9cb5-e001bde73e21.png)

**Comment by Everrest1** [comment]
Конструктор явно перегружен [п.1.12](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#1.12)

![image](https://user-images.githubusercontent.com/43137324/122873059-fdd31d80-d339-11eb-9974-0e6a47301592.png)

**Comment by Everrest1** [comment]
Класс блока - это часть его _внутренней_ реализации, о которой не должны знать другие блоки

![image](https://user-images.githubusercontent.com/43137324/122873365-586c7980-d33a-11eb-9a13-7231408ad2ea.png)

**Comment by n0sfer666** [comment]
> Разные классы у элемента
> 
> ![image](https://user-images.githubusercontent.com/43137324/122872601-5a820880-d339-11eb-9cb5-e001bde73e21.png)

исправил (60d81d5)

**Comment by n0sfer666** [comment]
> Класс блока - это часть его _внутренней_ реализации, о которой не должны знать другие блоки
> 
> ![image](https://user-images.githubusercontent.com/43137324/122873365-586c7980-d33a-11eb-9a13-7231408ad2ea.png)

Исправил (85b3120)

**Comment by n0sfer666** [comment]
> Конструктор явно перегружен [п.1.12](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#1.12)
> 

Испавил во всех конструкторах (cc019f5, 420ee3f, b2040bf, 33ac02f)

**Comment by Everrest1** [comment]
В миксине можно указать пустой объект значением по-умолчанию и не нужно будет передавать его при инициализации.

Нужны ещё примеры использования плагина с частичной передачей параметров, например, только максимальное значение и шаг, и т.п. Это нужно, чтобы слайдер самостоятельно подставил недостающие значения.

![image](https://user-images.githubusercontent.com/43137324/124425380-2105c000-dd71-11eb-8096-98e7d1da2df1.png)

**Comment by Everrest1** [comment]
Глобальные стили нужно вынести из блока

![image](https://user-images.githubusercontent.com/43137324/124428682-b0ad6d80-dd75-11eb-804d-c5dff8acb2c7.png)

**Comment by Everrest1** [comment]
Для чего здесь заполнять этот массив?

![image](https://user-images.githubusercontent.com/43137324/124428970-f2d6af00-dd75-11eb-9e45-96c99cf33d3e.png)

**Comment by Everrest1** [comment]
Инициализировать слайдер нужно так, как это будет делать потенциальный пользователь, т.е. как jQuery плагин
`$('.slider).SimpleRangeSlider(options)`

![image](https://user-images.githubusercontent.com/43137324/124430037-544b4d80-dd77-11eb-9136-4c4832b29cc8.png)

**Comment by n0sfer666** [comment]
> В миксине можно указать пустой объект значением по-умолчанию и не нужно будет передавать его при инициализации.
> 
> Нужны ещё примеры использования плагина с частичной передачей параметров, например, только максимальное значение и шаг, и т.п. Это нужно, чтобы слайдер самостоятельно подставил недостающие значения.
> 

Переделал 9fbdc7f
В первый миксин передал неправильный параметр, вместо пустого объекта и переделал getSliderConfig

**Comment by n0sfer666** [comment]
> Глобальные стили нужно вынести из блока
> 

переместил в pages/index.scss (097c5ae)

**Comment by n0sfer666** [comment]
> Для чего здесь заполнять этот массив?
> 

```js
jQuery(document).ready(() => {
  const $demoPanels = $('.js-demo-panel');
  $.each($demoPanels, (_, element) => {
    // eslint-disable-next-line no-new
    new DemoPanel($(element));
  });
});
```
так сделал c2ad6f5

**Comment by n0sfer666** [comment]
> Инициализировать слайдер нужно так, как это будет делать потенциальный пользователь, т.е. как jQuery плагин
> `$('.slider).SimpleRangeSlider(options)`
> 

Сделал вот так:
1) 13f99e6 - добавил в контейнер слайдера конфиг без инпута (в дату)
2) 504aca2 de4c839 f777e41 - переделал скрипты блоков демо-панели

**Comment by Everrest1** [comment]
Тут можно без js сделать

![image](https://user-images.githubusercontent.com/43137324/124948848-bd51f000-e019-11eb-92f3-41f54d242c8e.png)

**Comment by n0sfer666** [comment]
Сделал так: a43d761
```js
  blinkInputAndReturnPreviousValue($input: JQuery, previousValue: number) {
    $input.removeClass(`${this.blockClass}__input_normal`);
    $input.addClass(`${this.blockClass}__input_wrong`);
    setTimeout(() => {
      $input.addClass(`${this.blockClass}__input_normal`);
      $input.removeClass(`${this.blockClass}__input_wrong`);
    }, 250);
    $input.val(previousValue);
  }
```

**Comment by Everrest1** [comment]
`border` из `_normal` можно вернуть обратно в блок. `setTimeout` можно попробовать убрать и заменить использованием css анимации

**Comment by n0sfer666** [comment]
> `border` из `_normal` можно вернуть обратно в блок. `setTimeout` можно попробовать убрать и заменить использованием css анимации

Попробовал сделать сначала так: $input.addClass().delay(250).removeClass(). Оказалось что в jQ delay очень специфическая функция и работает только со всякими fadeIn, fadeOut.
Попробовал сделать css анимацию, но здесь концептуально ничего не поменять, нужен таймер, который удалит анимацию, чтобы потом снова её запустить.
По итогу вернулся к первоначальному варианту просто убрал модификатор _normal 6edce9e

**Comment by Everrest1** [comment]
В head нужно добавить [теги](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#2.5)

![image](https://user-images.githubusercontent.com/43137324/130918702-b1d79bd4-6f17-43fa-a52e-be6e4133e08a.png)

**Comment by n0sfer666** [comment]
Добавил (c8d81cc):
```js
meta(name="description", content='Demonstration of Simple Range Slider plugin')
meta(name="keywords", content='slider, rangeSlider, simpleRangeSlider')
title Simple Range Slider Demo Page
```

**Comment by Everrest1** [comment]
favicon ещё не хватает [П.3.2.](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#3.2)

**Comment by n0sfer666** [comment]
> favicon ещё не хватает [П.3.2.](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#3.2)

Сделано (28afb6a eb7b4c5 a01b6a3)
