### ISSUE TITLE
Шкала

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/FSD-Task-4-v3#10]
Не совсем верно она отображает положение бегунка

![image](https://user-images.githubusercontent.com/43137324/124951878-6d285d00-e01c-11eb-91e3-c918f8699c74.png)

**Comment by n0sfer666** [comment]
Исправил e3e4cb2

**Comment by Everrest1** [comment]
Деления прилипли к цифрам

![image](https://user-images.githubusercontent.com/43137324/125310001-df5db200-e33a-11eb-85ac-7678b93106d7.png)

**Comment by n0sfer666** [comment]
> Деления прилипли к цифрам
> 
Странно. У меня нет (проверил в двух разных браузерах):
![image](https://user-images.githubusercontent.com/21785370/125420397-3045c1e3-3641-4861-b173-eac4e1c8c46a.png)

**Comment by n0sfer666** [comment]
Отодвинул 4335971

**Comment by n0sfer666** [comment]
Сделал небольшую модификацию установки засечек шкалы 71d9909
