### ISSUE TITLE
Данные

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/FSD-Task-4-v3#11]
В чём разница между start и control?

![image](https://user-images.githubusercontent.com/43137324/125314398-d373ef00-e33e-11eb-83fb-52802cf32829.png)

**Comment by Everrest1** [comment]
Этот класс часть модели? Презентер? Сейчас в принципе не очень понятно, где хранятся настройки слайдера

![image](https://user-images.githubusercontent.com/43137324/125315488-dcb18b80-e33f-11eb-84ec-5e5e43ee3a89.png)

**Comment by n0sfer666** [comment]
> В чём разница между start и control?
> 
> ![image](https://user-images.githubusercontent.com/43137324/125314398-d373ef00-e33e-11eb-83fb-52802cf32829.png)

start - стартовые значения,
control - изменения значений слайдера на лету (был такой пункт в тексте задания).
**Пример.** 
Если ты попытаешься задать значение control, выходящее за рамки допустимых значений, подставится максимально возможное. 
Если тоже повторить со start, поле мигнёт красным и значение вернётся к предыдущему.

Заметил баг. При изменении значений слайдера на лету (блок control) меняется start. Исправил cff866b 766e13b

> Этот класс часть модели? Презентер? Сейчас в принципе не очень понятно, где хранятся настройки слайдера
> 
> ![image](https://user-images.githubusercontent.com/43137324/125315488-dcb18b80-e33f-11eb-84ec-5e5e43ee3a89.png)

Это класс в котором собираются модель, вид, презентер. Здесь же хранится конфиг. Олег, я не совсем понял, в чем здесь проблема. Опиши подробней, плиз.

**Comment by Everrest1** [comment]
> start - стартовые значения,
control - изменения значений слайдера на лету (был такой пункт в тексте задания).
Пример.
Если ты попытаешься задать значение control, выходящее за рамки допустимых значений, подставится максимально возможное.
Если тоже повторить со start, поле мигнёт красным и значение вернётся к предыдущему.

Выглядит как-то странно и не понятно. Они по сути делают одно и тоже, но с разным результатом) Т.е. у тебя 2 способа задать текущее значение бегунков) Окей. Кстати, это было бы проще понять, если бы была документация :/

**Comment by Everrest1** [comment]
> Это класс в котором собираются модель, вид, презентер. Здесь же хранится конфиг. Олег, я не совсем понял, в чем здесь проблема. Опиши подробней, плиз.

MVP модель подразумевает разделение приложения на логические слои, отвечающие за различные приложения. Из названия слоёв. View - отвечает за отображение данных и взаимодействие с пользователем, пассивная view ничего не знает об остальных слоях, данные в неё попадают сверху. Model - отвечает за хранение и расчёт всех данных в приложении, она не должна знать о существовании других слоёв. Presenter(или Controller) - знает об остальных слоях и нужен для организации взаимодействия остальных слоёв, путём добавления подписок, методов выдачи данных, он не производит никаких расчётов или взаимодействия с браузером.
Как-то так вкратце, у тебя есть эта структура, но она размыта классом SimpleRangeSlider, потому и спрашиваю к какому слою он относится и где находится источник истины для настроек слайдера

**Comment by n0sfer666** [comment]
> > start - стартовые значения,
> > control - изменения значений слайдера на лету (был такой пункт в тексте задания).
> > Пример.
> > Если ты попытаешься задать значение control, выходящее за рамки допустимых значений, подставится максимально возможное.
> > Если тоже повторить со start, поле мигнёт красным и значение вернётся к предыдущему.
> 
> Выглядит как-то странно и не понятно. Они по сути делают одно и тоже, но с разным результатом) Т.е. у тебя 2 способа задать текущее значение бегунков) Окей. Кстати, это было бы проще понять, если бы была документация :/

Ты не совсем понял. Поле start существует только в demo-panel'е, а в рабочем проекте это просто строчка конфига. А control - это отображение значений, как вот здесь:
![image](https://user-images.githubusercontent.com/21785370/126526591-88c795d0-baf8-4fe2-a496-9ce7e4741643.png)
![image](https://user-images.githubusercontent.com/21785370/126526711-ae4105cf-a7a5-46b1-af40-c1a119815dae.png)
Напишу документацию, станет понятней :)

**Comment by n0sfer666** [comment]
> > Это класс в котором собираются модель, вид, презентер. Здесь же хранится конфиг. Олег, я не совсем понял, в чем здесь проблема. Опиши подробней, плиз.
> 
> MVP модель подразумевает разделение приложения на логические слои, отвечающие за различные приложения. Из названия слоёв. View - отвечает за отображение данных и взаимодействие с пользователем, пассивная view ничего не знает об остальных слоях, данные в неё попадают сверху. Model - отвечает за хранение и расчёт всех данных в приложении, она не должна знать о существовании других слоёв. Presenter(или Controller) - знает об остальных слоях и нужен для организации взаимодействия остальных слоёв, путём добавления подписок, методов выдачи данных, он не производит никаких расчётов или взаимодействия с браузером.
> Как-то так вкратце, у тебя есть эта структура, но она размыта классом SimpleRangeSlider, потому и спрашиваю к какому слою он относится и где находится источник истины для настроек слайдера

Я понял свою ошибку. Да, класс SimpleRangeSlider по сути был куском контроллера. В 8c7e5a7 я сделал архитектуру более "прозрачной".

**Comment by n0sfer666** [comment]
Переделал.
