### ISSUE TITLE
Документация

### ISSUE THREAD

**Issue by n0sfer666** [n0sfer666/FSD-Task-4-v3#12]
1. В README проекта нужно добавить описание вашей архитектуры.
  2. После проектирования слоёв приложения, в README вам нужно написать, как вы отвязываете ваши слои приложений от внешних зависимостей, и осуществляете передачу данных снизу-вверх по слоям приложения. Возможно, вы обратили внимание, что получившиеся слои не являются равнозначными: есть слои с высокими уровнями абстракции, а есть — с низкими. Помимо этого, возможно, вы заметили, что каждый класс вашей архитектуры отвечает за отдельный аспект приложения.
  3. Помимо этого, вы должны составить UML-диаграмму своего приложения, которую тоже нужно добавить в README. Программа для составления диаграммы: https://www.draw.io/

**Comment by n0sfer666** [comment]
> 2. После проектирования слоёв приложения, в README вам нужно написать, как вы отвязываете ваши слои приложений от внешних зависимостей, и осуществляете передачу данных снизу-вверх по слоям приложения. Возможно, вы обратили внимание, что получившиеся слои не являются равнозначными: есть слои с высокими уровнями абстракции, а есть — с низкими. Помимо этого, возможно, вы заметили, что каждый класс вашей архитектуры отвечает за отдельный аспект приложения.

Олег, объясни, пожалуйста, что здесь написано :) Что значит "отвязываете ваши слои"? Что значит "высокий/низкий уровень абстракции"?

**Comment by Everrest1** [comment]
> Что значит "отвязываете ваши слои"? 

Ну это как раз изоляция слоёв MVP, где модель или отображение не знают о друг друге

> Что значит "высокий/низкий уровень абстракции"?

Про это лучше на каком-нибудь ресурсе почитать, например, [здесь](https://techrocks.ru/2020/04/09/abstraction-levels-in-software-development/)
