### ISSUE TITLE
Инпуты в плагине

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/FSD-Task-4-v3#13]
В плагине не должно быть заложено дополнительных элементов управления помимо api и самого слайдера. Это сильно ограничивает его возможное использование на конкретном случае, который, скорее всего, и не понадобится большинству пользователей). Смысл плагина в универсальности предоставления своего функционала и независимости от возможных вариантов его использования

![image](https://user-images.githubusercontent.com/43137324/130926078-44750a4f-4d76-4826-a569-ad12d8a75bdc.png)

**Comment by n0sfer666** [comment]
![image](https://user-images.githubusercontent.com/21785370/130974210-b8b084c1-ac6d-444a-afd0-0e1f6f2dea69.png)

Т.е. это (требование) не об этом (класс InputCheckboxTooltip)?

**Comment by Everrest1** [comment]
Не совсем, это требование о том, что нужно реализовать в плагине элемент, `который показывает значение и ползает за мышкой`, а возможность включать/отключать устанавливается просто параметром в конфиге.

А вообще имел ввиду вот это. Что не нужно прокидывать в слайдер какие-то элементы управления из вне. Пользователь сам будет выбирать каким образом подписываться на слайдер или как доставать из него значения
![image](https://user-images.githubusercontent.com/43137324/131082897-9ed2ff1a-a263-41a7-bdf1-15c988abb67a.png)
![image](https://user-images.githubusercontent.com/43137324/131082980-fef2c46b-c386-4a69-8a92-0e2b96b294b1.png)

**Comment by n0sfer666** [comment]
Убрал класс и почистил проект от его присутствия 
767cdcd

**Comment by Everrest1** [comment]
А этот класс что делает? По коду я так и не понял

![image](https://user-images.githubusercontent.com/43137324/131366872-af14715a-31f3-4274-b4f8-bc6b162cd6da.png)

**Comment by n0sfer666** [comment]
> А этот класс что делает? По коду я так и не понял
> 
> ![image](https://user-images.githubusercontent.com/43137324/131366872-af14715a-31f3-4274-b4f8-bc6b162cd6da.png)

Это для работы вот этой штуки:
![image](https://user-images.githubusercontent.com/21785370/131502281-883ffd39-9443-460d-84f8-7987aab8e03d.png)
Так как эта штука в реальных условиях будет использована в 99% случаев, я сделал её на уровне конфига:
![image](https://user-images.githubusercontent.com/21785370/131505602-d7cd29d4-126d-4f20-bc80-cdd9b4da78d8.png)
```js
type ConfigInputs = {
  values?: [JQuery] | [JQuery, JQuery],
};
```

**Comment by Everrest1** [comment]
> Так как эта штука в реальных условиях будет использована в 99% случаев, я сделал её на уровне конфига:

А я думаю, что эта штука в 99% случаев использоваться не будет, кроме как некоторых в тестовых примерах. Зачем ещё раз выводить в интерфейс значение слайдера, если у нас есть сам слайдер?
