### ISSUE TITLE
Разные правки

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/FSD-Task-4-v3#14]
Метод find всегда возвращает jQuery объект и левая часть выражения всегда будет true

![image](https://user-images.githubusercontent.com/43137324/131360084-44d5c0c9-93fa-42e4-bd71-facc1b62dc08.png)

**Comment by n0sfer666** [comment]
Хотел бы что-то ответить, но сам не знаю зачем так написал =\

**Comment by Everrest1** [comment]
Это условие можно использовать и здесь

![image](https://user-images.githubusercontent.com/43137324/133386016-c2c959a5-80b6-43b3-a261-6d9e16176f5d.png)

**Comment by Everrest1** [comment]
Тут надо бы сделать перенос строки

![image](https://user-images.githubusercontent.com/43137324/133387667-201e8c6b-16a0-4187-a80a-efd3ed619fbe.png)

**Comment by n0sfer666** [comment]
> Это условие можно использовать и здесь
> 
> ![image](https://user-images.githubusercontent.com/43137324/133386016-c2c959a5-80b6-43b3-a261-6d9e16176f5d.png)

Тогда получается вот так:
![image](https://user-images.githubusercontent.com/21785370/133395211-135332a9-ab98-44b8-a0b3-6f2e3123ab4b.png)
Исправил non-null assertion'ом

**Comment by n0sfer666** [comment]
> Тут надо бы сделать перенос строки
> 
> ![image](https://user-images.githubusercontent.com/43137324/133387667-201e8c6b-16a0-4187-a80a-efd3ed619fbe.png)

сделано (948c015)

**Comment by Everrest1** [comment]
> Исправил non-null assertion'ом

Теперь тут лучше, если условие будет внутри if и без assertion :). А вообще, я не увидел, что там и тип сужается, в таких случаях проверку лучше продублировать или написать свой защитник типа, чем прибегать к non-null assertion

![image](https://user-images.githubusercontent.com/43137324/133754838-07d3f5ed-44b1-428b-8d47-ac107b56663a.png)

**Comment by Everrest1** [comment]
Тут мне кажется деструктуризация выглядит лишней

![image](https://user-images.githubusercontent.com/43137324/133757458-eb9d846e-4f20-49f1-8b9f-8ff1ff5c7c88.png)

**Comment by n0sfer666** [comment]
> > Исправил non-null assertion'ом
> 
> Теперь тут лучше, если условие будет внутри if и без assertion :). А вообще, я не увидел, что там и тип сужается, в таких случаях проверку лучше продублировать или написать свой защитник типа, чем прибегать к non-null assertion
> 

Заменил защитниками типа 7804ec4
```js
typeof variables[1] === 'number'
```

**Comment by n0sfer666** [comment]
> Тут мне кажется деструктуризация выглядит лишней
> 

Просто хотел избежать такого
```js
    this.callbackList.forEach((callback) => callback({
      index: this.index,
      position: this.position,
    }));
```
Заменил 17f6235

**Comment by Everrest1** [comment]
В jquery же можно создавать dom узлы и классы сразу [закинуть](https://api.jquery.com/jQuery/#jQuery2)

![image](https://user-images.githubusercontent.com/43137324/134698174-bf09cf29-f718-4deb-8a13-f539e957432c.png)

А почему бы не поднять деструктуризацию на самый верх тела функции и работать уже с переменными?

![image](https://user-images.githubusercontent.com/43137324/134699151-b8e4ab8b-fce9-4a80-92a8-ef87ea6cb009.png)

**Comment by Everrest1** [comment]
Фигурные скобки лучше всегда разворачивать, посмотри везде плиз

![image](https://user-images.githubusercontent.com/43137324/134699934-4db90a06-a342-4d8b-bbb6-60d8a6dbde26.png)

**Comment by n0sfer666** [comment]
> Фигурные скобки лучше всегда разворачивать, посмотри везде плиз
> 
> ![image](https://user-images.githubusercontent.com/43137324/134699934-4db90a06-a342-4d8b-bbb6-60d8a6dbde26.png)

Это было одно единственное место 3c5bdac

**Comment by n0sfer666** [comment]
> В jquery же можно создавать dom узлы и классы сразу [закинуть](https://api.jquery.com/jQuery/#jQuery2)
> 

Сделал так bb44019

**Comment by n0sfer666** [comment]
> А почему бы не поднять деструктуризацию на самый верх тела функции и работать уже с переменными?
> 

Сделал 1a236a6. Когда добавлял переменные (ctrl + space), заметил, что у меня во ViewUpdateList проскочил step. Убрал Omit'ом.

**Comment by Everrest1** [comment]
range всегда будет true
this.entities.scale можно поместить в isRangeChanged, так останется всего одна if вместо трёх

![image](https://user-images.githubusercontent.com/43137324/135033397-fc54c5e9-04e8-4b7a-a605-6decaf395f81.png)

Нужно в именовании явно обозначить, что переменные принадлежат к типу boolean

![image](https://user-images.githubusercontent.com/43137324/135033839-033eaf4f-b643-4537-99e1-edbbbebad8f6.png)

``

ViewUpdateList похоже тоже не нужен) 
Здесь можно дополнить недостающие значения после спред config из this.config, тогда у тебя из метода будет возвращаться конфиг со всеми актуальными значениями.

![image](https://user-images.githubusercontent.com/43137324/135034694-313f13a7-fc60-484a-8e34-d02031a12be6.png)

А тут ты и так всегда сравниваешь с предыдущими значениями, а проверку на undefined можно будет убрать

![image](https://user-images.githubusercontent.com/43137324/135034980-30505d89-4bcd-4c81-a250-9f4652b51d3f.png)

Причём где-то даже дважды

![image](https://user-images.githubusercontent.com/43137324/135035181-7b0a8cdb-9d0a-4361-854a-75273a0b3585.png)

**Comment by Everrest1** [comment]
Со строчной буквы

![image](https://user-images.githubusercontent.com/43137324/135035346-3c04fcaa-7f4b-48f3-a067-7365acc0eb98.png)

В чём разница между использованием null и undefined?) В интервью будет такой ворос :)

![image](https://user-images.githubusercontent.com/43137324/135035999-31273342-f450-42f2-ab26-3a926006c83b.png)

**Comment by n0sfer666** [comment]
> range всегда будет true this.entities.scale можно поместить в isRangeChanged, так останется всего одна if вместо трёх
> 
> 
> Нужно в именовании явно обозначить, что переменные принадлежат к типу boolean
> 
> 
> ``
> 
> ViewUpdateList похоже тоже не нужен) Здесь можно дополнить недостающие значения после спред config из this.config, тогда у тебя из метода будет возвращаться конфиг со всеми актуальными значениями.
> 
> 
> А тут ты и так всегда сравниваешь с предыдущими значениями, а проверку на undefined можно будет убрать
> 
> 
> Причём где-то даже дважды
> 

> Со строчной буквы
> 
> ![image](https://user-images.githubusercontent.com/43137324/135035346-3c04fcaa-7f4b-48f3-a067-7365acc0eb98.png)
> 
> В чём разница между использованием null и undefined?) В интервью будет такой ворос :)
> 
> ![image](https://user-images.githubusercontent.com/43137324/135035999-31273342-f450-42f2-ab26-3a926006c83b.png)


Всё исправил и нашёл классный ответ на вопрос чем отличается undefined и null
![image](https://user-images.githubusercontent.com/21785370/135218251-5ea5f79a-015a-4f75-98c1-e8e36f0d1e09.png)

**Comment by Everrest1** [comment]
Тут ещё осталось 

![image](https://user-images.githubusercontent.com/43137324/136034304-50bf69fa-539c-4476-be1a-5675ac01b802.png)
![image](https://user-images.githubusercontent.com/43137324/136034341-008265d5-c9ca-4795-8115-38411b49a326.png)
