### ISSUE TITLE
Компановка методов

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/FSD-Task-4-v3#15]
Нужно как-то порефактрорить и упростить, побить на несколько методов. Читать код с большой вложенностью условий тяжело

![image](https://user-images.githubusercontent.com/43137324/131361473-537bd662-4cd4-4b5a-94ea-05c6f1591a7f.png)

**Comment by Everrest1** [comment]
Кажется эти проверки должны быть внутри слайдера. Плагин должен быть устойчивым к любым невалидным значениям и не ломаться, независимо откуда они поступают: из интерфейса, атрибутов или методами инициализации, обновления.

![image](https://user-images.githubusercontent.com/43137324/131362599-13630db6-378f-4d7f-ae4f-9789e62ee8c9.png)

**Comment by n0sfer666** [comment]
> Кажется эти проверки должны быть внутри слайдера. Плагин должен быть устойчивым к любым невалидным значениям и не ломаться, независимо откуда они поступают: из интерфейса, атрибутов или методами инициализации, обновления.
> 

Эта верификация происходит в Моделе (метод getVerifiedConfig).
Здесь это сделано, чтобы подсветить элемент красной рамкой в случае неправильного значения.

**Comment by n0sfer666** [comment]
> Нужно как-то порефактрорить и упростить, побить на несколько методов. Читать код с большой вложенностью условий тяжело
> 
Теперь выглядит так:
```js
  handleButtonClick() {
    this.sliderConfig = this.sliderInstance.getConfig();
    if (this.isSinglePointer) {
      this.addPointerIfPossible();
    } else {
      this.removePointer();
    }
  }

  addPointerIfPossible() {
    const {
      start, range, step, input,
    } = this.sliderConfig;
    const newValue = step < 10
      ? start[0] + 10
      : start[0] + step;
    if (newValue < range[1]) {
      this.isSinglePointer = false;
      start.push(newValue);
      input!.values![1].show();
      this.$secondStart.show().val(start[1]!);
      this.sliderInstance.updateSlider({ start });
      this.$text.text('remove pointer');
    } else {
      this.$container.addClass(`${this.blockClass}_wrong-condition`);
      setTimeout(() => {
        this.$container.removeClass(`${this.blockClass}_wrong-condition`);
      }, 300);
    }
  }

  removePointer() {
    const { start, input } = this.sliderConfig;
    this.isSinglePointer = true;
    start.pop();
    input!.values![1].hide();
    this.$secondStart.hide().val('');
    this.sliderInstance.updateSlider({ start });
    this.$text.text('add pointer');
  }
```

**Comment by Everrest1** [comment]
> Эта верификация происходит в Моделе (метод getVerifiedConfig).
Здесь это сделано, чтобы подсветить элемент красной рамкой в случае неправильного значения.

То есть одинаковая валидация в двух местах. Можно сделать проще: после передачи значения слайдеру проверять поменял он внутреннее состояние на переданное значение или нет

**Comment by Everrest1** [comment]
non-null assertions используются только в самых крайних случаях, когда по-другому никак не сделать, пройдись, плиз, по всему проекту

![image](https://user-images.githubusercontent.com/43137324/132457418-5c644c23-355a-4dec-a49d-8d5680ed5ec9.png)

**Comment by n0sfer666** [comment]
> non-null assertions используются только в самых крайних случаях, когда по-другому никак не сделать, пройдись, плиз, по всему проекту
> 

non-null assertions ware destroyed (5cb087c)

**Comment by Everrest1** [comment]
Этот метод явно требует рефакторинга. Как минимум, управление тултипами можно убрать в pointers. А обновление позиций у тебя уже реализовано в метода updateByModel

![image](https://user-images.githubusercontent.com/43137324/133034437-86c07694-ddec-480b-8384-d9c93e0b0f80.png)

**Comment by n0sfer666** [comment]
Не совсем понял что значит "управление тултипами можно убрать в pointers"...
С остальным, вроде, справился.

**Comment by Everrest1** [comment]
> Не совсем понял что значит "управление тултипами можно убрать в pointers"...
> С остальным, вроде, справился.

Инициализацию new Tooltip и метод updateTools нужно поместить в класс Pointer, таким образом ответсвенность за них перейдёт из главной вью на соответствующий тултипу бегунок

**Comment by n0sfer666** [comment]
> Инициализацию new Tooltip и метод updateTools нужно поместить в класс Pointer, таким образом ответсвенность за них перейдёт из главной вью на соответствующий тултипу бегунок

Сделано 8088105

**Comment by Everrest1** [comment]
Я думаю более логично будет, если обновлять значения tooltip будет тоже pointer

![image](https://user-images.githubusercontent.com/43137324/133755862-8fd04a60-0f91-45a0-b9c4-ec569db6204c.png)

**Comment by Everrest1** [comment]
А модель в конструкторе разве не делает тоже самое?

![image](https://user-images.githubusercontent.com/43137324/133757094-ea8f948c-053e-420d-98a4-ffc7a8a2d959.png)
![image](https://user-images.githubusercontent.com/43137324/133757176-4c99620e-101a-4b92-af33-7c71381d2147.png)

**Comment by n0sfer666** [comment]
> Я думаю более логично будет, если обновлять значения tooltip будет тоже pointer
> 

Не совсем понял... значение tooltip'а обновляет pointer. Сделал так db41762

**Comment by n0sfer666** [comment]
> А модель в конструкторе разве не делает тоже самое?
> 

Делает ^_^
Исправил 2b77b2f
