### ISSUE TITLE
Конфиг

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/FSD-Task-4-v3#16]
Поле config и так содержит в себе range, step. Потом у тебя идёт values, и pointers, которые имеют один и тот же тип, и по названиям непонятно что это) Да, ты мне объяснял, но я забыл, нужно как-то это обозначить в коде.
+Из-за дублирования при изменении значения нужно обновлять его везде, и если где-то забыть, то будет невозможно определить какое из них верное

![image](https://user-images.githubusercontent.com/43137324/131364140-396efc5f-8042-4f2c-ac79-f5928766b8f1.png)

![image](https://user-images.githubusercontent.com/43137324/131364035-3ad5abb9-7467-497e-90a8-b33e0237f443.png)

**Comment by Everrest1** [comment]
Зачем?

![image](https://user-images.githubusercontent.com/43137324/131365324-8d2614dd-6ce9-4e44-8bac-07cba40674c2.png)

**Comment by Everrest1** [comment]
Если это `start`, то почему он принимает ещё и конечное значение? `{ start: [start: string; end: string] }`

![image](https://user-images.githubusercontent.com/43137324/131365735-e8804a6c-c4de-4a93-b03a-f6463a6de01b.png)

**Comment by Everrest1** [comment]
Тут три почти идентичных интерфейса. Если `?` можно добавить используя `Partial<T>`, если это так необходимо, то в полезности ViewUpdateList я сомневаюсь, может лучше использовать один универсальный конфиг, чтобы не было путаницы и лишних преобразований объектов?

![image](https://user-images.githubusercontent.com/43137324/131365896-5724a7a6-ff00-4b97-88d0-be04214dfe82.png)
![image](https://user-images.githubusercontent.com/43137324/131365916-14887678-696b-44ee-ba30-2cb6b1c08131.png)

**Comment by n0sfer666** [comment]
> Зачем?
> 
> ![image](https://user-images.githubusercontent.com/43137324/131365324-8d2614dd-6ce9-4e44-8bac-07cba40674c2.png)

Чтобы избегать таких ошибок:
```
TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'CompleteConfigList'.
  No index signature with a parameter of type 'string' was found on type 'CompleteConfigList'.
```
Компилятор TS при использовании метода  each (jQuery), хочет чтобы ему на уровне типов указали что ключи объектов string.

**Comment by n0sfer666** [comment]
> Если это `start`, то почему он принимает ещё и конечное значение? `{ start: [start: string; end: string] }`
> 
> ![image](https://user-images.githubusercontent.com/43137324/131365735-e8804a6c-c4de-4a93-b03a-f6463a6de01b.png)

Это не конечное значение, а значение второго бегунка (при создании плагина).
Т.е. если start: [0], создаётся 1 бегунок, а если start: [0, 10], то создаются 2 бегунка.
Этот тип специально ограничивает создание слайдера с более чем 2мя бегунками.
[Documentation](https://github.com/n0sfer666/FSD-Task-4-v3/blob/master/README.md#%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)

**Comment by n0sfer666** [comment]
> Тут три почти идентичных интерфейса. Если `?` можно добавить используя `Partial<T>`, если это так необходимо, то в полезности ViewUpdateList я сомневаюсь, может лучше использовать один универсальный конфиг, чтобы не было путаницы и лишних преобразований объектов?
> 
Переделал ещё и ...Data
```js
interface ObjectKeyString {
  [key: string]: any;
}
interface SliderData extends ObjectKeyString {
  position?: number,
  positions: PointerPosition,
  value?: number,
  values: PointerValue,
  index: number
}
type ViewData = Pick<SliderData, 'position' | 'value' | 'index'>;
type PointerData = Required<Pick<SliderData, 'position' | 'index'>>;
type ScaleData = Required<Pick<SliderData, 'value'>>;
type InputTextData = Required<Pick<SliderData, 'value' | 'index'>>;
type ModelData = Pick<SliderData, 'positions' | 'values' | 'index'>;
interface UserConfigList extends ObjectKeyString {
  orientation?: ConfigOrientation;
  start?: PointerValue;
  range?: ConfigRange;
  step?: number;
  connect?: boolean;
  tooltip?: boolean;
  scale?: boolean;
  input?: ConfigInputs;
}
interface CompleteConfigList extends Required<UserConfigList> {
}
interface ViewConfigList extends Pick<CompleteConfigList, 'orientation' | 'connect' | 'tooltip' | 'scale' | 'input'> {
}
interface ViewUpdateList extends Partial<ViewConfigList> {
  positions?: PointerValue,
  values?: PointerValue,
  range?: ConfigRange,
}
```

**Comment by Everrest1** [comment]
> > Если это `start`, то почему он принимает ещё и конечное значение? `{ start: [start: string; end: string] }`
> > ![image](https://user-images.githubusercontent.com/43137324/131365735-e8804a6c-c4de-4a93-b03a-f6463a6de01b.png)
> 
> Это не конечное значение, а значение второго бегунка (при создании плагина).
> Т.е. если start: [0], создаётся 1 бегунок, а если start: [0, 10], то создаются 2 бегунка.
> Этот тип специально ограничивает создание слайдера с более чем 2мя бегунками.
> [Documentation](https://github.com/n0sfer666/FSD-Task-4-v3/blob/master/README.md#%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)

Я и имел ввиду значение второго бегунка. Слайдер, который позволяет указать промежуток значений подразумевает, что у него есть начало (start) и конец (end). Поэтому мне кажется, что по имени данного параметра не очень понятно что это

![image](https://user-images.githubusercontent.com/43137324/132458913-f265c647-e5d4-407d-b1b0-8bf5628b1d3f.png)

**Comment by n0sfer666** [comment]
> Я и имел ввиду значение второго бегунка. Слайдер, который позволяет указать промежуток значений подразумевает, что у него есть начало (start) и конец (end). Поэтому мне кажется, что по имени данного параметра не очень понятно что это
> 
Кажется теперь я понял, о чём ты))
Переименовал в values (b01dd00 dc3dcdc)
