### ISSUE TITLE
Connect

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/FSD-Task-4-v3#17]
Для чего инициализировать this.position дважды?

![image](https://user-images.githubusercontent.com/43137324/133759489-0d2b0d63-92db-40a1-a029-5c9b10ee12e2.png)

Одного источника данных будет достаточно, `valuesPosition, endPosition` либо `positions`

![image](https://user-images.githubusercontent.com/43137324/133759640-9010a0aa-58d8-45e4-a3dc-98868d3b5238.png)

`endPosition` есть, а `startPosition` нет, хотелось бы более интуитивно понятное имя

![image](https://user-images.githubusercontent.com/43137324/133759850-fbfa6d8b-2e86-46b5-92ea-cc3e0bdbbda0.png)

**Comment by n0sfer666** [comment]
Исправил.
![image](https://user-images.githubusercontent.com/21785370/133882428-8aa6238a-0b4b-4db0-a784-53f443b1bc79.png)
