### ISSUE TITLE
Константы для классов

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/FSD-Task-4-v3#18]
Где-то у тебя собирается из частей, где-то полностью передаётся, где-то захардкожено. Давай приведём всё к одному виду. Либо выносим все определения классов в константы, либо пишем их полностью на месте

![image](https://user-images.githubusercontent.com/43137324/134189013-0f71d6da-0711-4124-a63d-2fd88aead239.png)
![image](https://user-images.githubusercontent.com/43137324/134188574-d8d58ce0-398d-4482-b7e1-c58cab282704.png)

А вот такой вариант лично мне очень тяжело читать и понять "что есть что"

![image](https://user-images.githubusercontent.com/43137324/134188037-a4cfa0e3-1198-4e50-bc87-cae834cf107d.png)

**Comment by n0sfer666** [comment]
Исправил. Надеюсь названия в шкале понятные :)
