### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/FSD-Task-4-v3#19]
Опять же у тебя есть конфиг, который уже храни в себе все эти значения и не понятно какие из них актуальные

![image](https://user-images.githubusercontent.com/43137324/134473453-0b5835e0-9dd0-45be-b92e-2b22d3321eda.png)

Я не вижу особого смысла так разделять значения конфига по разным методам. Ведь проще сразу получить весь конфиг и использовать только то, что нужно?)

![image](https://user-images.githubusercontent.com/43137324/134473505-ea10c783-88b7-404e-a96f-0b2284f13ddd.png)
![image](https://user-images.githubusercontent.com/43137324/134473535-8e778f65-3e06-4ba1-b344-5ba79749d31a.png)
![image](https://user-images.githubusercontent.com/43137324/134473600-958c4043-c512-41d0-a128-eba808018ef5.png)

**Comment by n0sfer666** [comment]
Исправил модель и сделал по аналогии тоже самое с вью

**Comment by Everrest1** [comment]
А точно здесь нужен activePointerIndex? Вроде ничего не делает

![image](https://user-images.githubusercontent.com/43137324/134695699-9baef6d2-ef62-4d74-b00f-6a98bc653c4f.png)

И я тогда можно преименовать index в activePointerIndex

![image](https://user-images.githubusercontent.com/43137324/134695883-c55542db-ae78-4062-9c41-d8807c621c0a.png)

**Comment by n0sfer666** [comment]
> А точно здесь нужен activePointerIndex? Вроде ничего не делает
> 
> ![image](https://user-images.githubusercontent.com/43137324/134695699-9baef6d2-ef62-4d74-b00f-6a98bc653c4f.png)
> 
> И я тогда можно преименовать index в activePointerIndex
> 
> ![image](https://user-images.githubusercontent.com/43137324/134695883-c55542db-ae78-4062-9c41-d8807c621c0a.png)

Исправил
