### ISSUE TITLE
Линтер

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/FSD-Task-4-v3#2]
Надо пофиксить ошибки линтера и добавить в package.json команду прохода линтера по проекту

**Comment by n0sfer666** [comment]
В package.json сделал 2 скрипта для линтера (с автофиксом и без): проходит все .ts файлы, кроме .d.ts (типы);
Отключил 2 правила: import/extensions и no-undef;
Пофиксил все ошибки;
Еще удалил демоПанель с тестами этой самой панели (надо было в отдельный коммит, но уже было поздно)

**Comment by Everrest1** [comment]
Я бы эти правила не отключал здесь

![image](https://user-images.githubusercontent.com/43137324/124361258-d41dce80-dc36-11eb-9aaf-6fda88d67aa3.png)

**Comment by n0sfer666** [comment]
> Я бы эти правила не отключал здесь
> 
> ![image](https://user-images.githubusercontent.com/43137324/124361258-d41dce80-dc36-11eb-9aaf-6fda88d67aa3.png)

Я могу убрать, но смысла особого нет (линтер игнорирует файлы *.d.ts), это сделано просто чтобы не бесило.
Можно конечно добавить import/export, но зачем? Все IDE автоматически подгружают *.d.ts и можно использовать все типы и интерфейсы, а не добавлять всё вручную нагружая код.
Но если это нужно, то проблем нет. Я могу это сделать

**Comment by Everrest1** [comment]
Да, и комментарии тоже здесь не нужны)

**Comment by n0sfer666** [comment]
Я нашел решение, благодаря которому не нужно вручную прописывать все импорты и экспорт.
Оно состоит в замене 'airbnb-base' на 'airbnb-typescript/base' 29087d8
Пожалуйста, скажи, что так можно!!! :sweat:

**Comment by Everrest1** [comment]
Надо ещё раз пройтись и пофиксить)

**Comment by n0sfer666** [comment]
> Надо ещё раз пройтись и пофиксить)

Сделано e328f5f

**Comment by Hahahayabanan** [comment]
Хм, что-то у меня всё-ещё много где подсвечивает

![image](https://user-images.githubusercontent.com/43137324/134187315-8051d3f9-66a9-46d4-b862-2b1da44cb385.png)
