### ISSUE TITLE
Тесты

### ISSUE THREAD

**Issue by n0sfer666** [n0sfer666/FSD-Task-4-v3#20]
Тестами должны быть покрыты все слои вашего приложения.

**Comment by Everrest1** [comment]
В вопросах по теории есть вопрос, почему одному тесту `test` должнен соответствовать один expect или один тип проверяемых значений `expect`, то есть, проверка должна быть для чего-то одного

Соответственно, например в этом тесте будет аж 40 проверок и если одна из них сфейлится, то будет сложно разобраться в каком месте что-то сломалось и что именно мы проверяли в данном тесте

![image](https://user-images.githubusercontent.com/43137324/141062293-eb59581f-8c56-4b14-b4c4-2a6f26c8bc14.png)


В заголовках группы тестов `describe` обычно указывается то, что мы тестируем, например, метод `updateByView`. В заголовке конкретного теста, описание того, какое поведение тестируемого метода/функции мы ожидаем

Например, как в идеале звучали бы некоторые заголовки для тестов для метода updateByView в модели: 
"Должен рассчитать значения и позицию бегунка в соответствии с шагом, если значение и позиция были переданы"
"Должен обновить значения бегунка максимальным значением, если переданная позиция выходит за границы"
"Должен вызвать такие-то колбеки"

![image](https://user-images.githubusercontent.com/43137324/141062498-444b6b6d-9ec0-4f04-9292-4b3b5e9a68b3.png)


Такой код выглядит очень странно для меня. Теперь не разобраться были вызваны эти expect или нет, или они вызываются через раз, или только для каких-то особенных случаев. В тестах не должно быть такой неочевидности

![image](https://user-images.githubusercontent.com/43137324/141063921-2fdc1ba7-5d31-4b8e-ad27-0fc9c1b8713c.png)
