### ISSUE TITLE
Сборка плагина

### ISSUE THREAD

**Issue by romansilivestrov** [n0sfer666/FSD-Task-4-v3#21]
![image](https://user-images.githubusercontent.com/85496220/147264521-2015d3a8-607a-4e3f-ae33-407a9a0e8db8.png)

Нет скрипта для сборки плагина, i.e. `npm run build`. На выходе должен получаться плагин, который можно подключить на любую страницу. Сейчас на демо странице всё идёт одним бандлом, а должно быть подключено три скрипта: отдельно JQuery, плагин и скрипт демо страницы.

**Comment by n0sfer666** [comment]
Извини, что так всё в один коммит вынес... заигрался.
npm run build создаёт в папке dist 4 файла: index.html, index.js, index.css (+ license)
В index.html подключен index.js и index.css.  Тип плагина 'umd':
![image](https://user-images.githubusercontent.com/21785370/149500754-81ed06dd-b6da-4016-b80e-8fa50af76dc5.png)
npm run build:jQuery тоже самое, но создаёт глобальный объект simpleRangeSlider в котором лежит расширенный jQuery:
![image](https://user-images.githubusercontent.com/21785370/149501139-81fc20b7-083e-41f3-89bf-1d8e5bb1d1c7.png)
npm start или npm run start - демо-панель

**Comment by n0sfer666** [comment]
Переделал
