### ISSUE TITLE
Unexpected behavior

### ISSUE THREAD

**Issue by romansilivestrov** [n0sfer666/FSD-Task-4-v3#23]
Второй ползунок принимает максимальное значение и не двигается:
![rightHandler](https://user-images.githubusercontent.com/85496220/147266091-359a58f7-b252-4e81-97ad-ce77de9d970d.gif)

При изменении значения шага в панели ничего не происходит:
![stepChange](https://user-images.githubusercontent.com/85496220/147266178-b8eb1719-2a9b-4432-adad-b86d029d5496.gif)

Инпут в демо панели не синхронизируется со значением ползунка:
![desync](https://user-images.githubusercontent.com/85496220/147266667-5f38905f-b1fa-4fcd-97d3-26c8618ea3c1.gif)

**Comment by n0sfer666** [comment]
Сделано

**Comment by n0sfer666** [comment]
Переделал синхронизацию значения бегунка с интуптом через callback.

**Comment by romansilivestrov** [comment]
После переключения количества ползунков прогрессбар ведёт себя некорректно:
![range](https://user-images.githubusercontent.com/85496220/150106176-b1cfcd58-ac3c-4af8-98ac-a17c6e33f3c7.gif)

**Comment by romansilivestrov** [comment]
При значении одиночного ползунка >= 90 второй не добавляется:
![image](https://user-images.githubusercontent.com/85496220/150107315-f21f83e8-54fb-46e4-9eb4-5882f95ead77.png)

**Comment by romansilivestrov** [comment]
После добавления второго ползунка он "прыгает" при первом перемещении:
![jump](https://user-images.githubusercontent.com/85496220/150108296-129b58a5-e796-4e3a-aeb6-245b6372303f.gif)

**Comment by n0sfer666** [comment]
Исправил + нашел ещё 2 бага и исправил тоже

**Comment by romansilivestrov** [comment]
- шкала не подстраивается под шаг;
- когда диапазон не кратен шагу, нельзя выбрать максимальное значение.
![scale](https://user-images.githubusercontent.com/85496220/150348227-ba3dc785-2089-49ab-a48a-24464705d315.gif)

**Comment by n0sfer666** [comment]
Исправил

**Comment by romansilivestrov** [comment]
- шкала всё ещё не подстраивается под шаг;
- через шкалу можно задать значения не кратные шагу;
- когда последний шаг шкалы неполный, возникает несоответствие положений курсора и ползунка;
- максимальное значение шкалы не всегда корректно;
![scale1](https://user-images.githubusercontent.com/85496220/150790061-34c144b1-5fc8-4a1a-a979-a1b2bd7906a3.gif)
![image](https://user-images.githubusercontent.com/85496220/150790102-07a8f940-c510-4139-ba71-09955eb354bf.png)

**Comment by n0sfer666** [comment]
Вроде всё сделал.
+ заметил кое какие узкие места в методе модели и исправил.

**Comment by romansilivestrov** [comment]
Ориентация и количество ползунков сбрасываются при автокорректировке значений min/max:
![reset](https://user-images.githubusercontent.com/85496220/151139220-89f3cb57-1b98-4211-82c6-3dabe0d353be.gif)
