### ISSUE TITLE
Тесты

### ISSUE THREAD

**Issue by sodiqit** [n0sfer666/FSD-Task-4-v3#25]
Упал тест
![изображение](https://user-images.githubusercontent.com/47000555/154264097-1509de9a-ee4b-470b-a66f-ed01488f18e2.png)

**Comment by n0sfer666** [comment]
Забыл удалить из кейса методы которые удалил из Scale 😥
+ Отрефакторил ещё кое-какие кейсы.
ЗЫ. в тестах будет часто встречаться странная конструкция:
```js
        setTimeout(() => {
          expect(expectedValue).toEqual(reciviedValue));
        }, 5);
```
Это кастыль, который возник из-за работы фреймворка jest (у него очень странный стек выполнения тестов)
