### ISSUE TITLE
best practice

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/FSD-Task-4-v3#3]
По best practice jquery плагинов метод инициализации плагина должен возвращать jquery объект

![image](https://user-images.githubusercontent.com/43137324/116972170-4ddf1d80-acc3-11eb-9585-9de25e05f955.png)

**Comment by n0sfer666** [comment]
Сделал так 45cde30326d7409f929ce65ef5cbc21fbb7ee8fc
```js
// eslint-disable-next-line func-names  
(function ($: JQueryStatic) {  
  $.fn.extend({  
    simpleRangeSlider(config: iConfigUser) {  
      // eslint-disable-next-line no-unused-vars  
      const slider = new SimpleRangeSlider(<JQuery> this, <iConfigUser> config);  
      return this;  
    },  
  });  
}(jQuery));`

**Comment by Everrest1** [comment]
Тогда const slider можно убрать, а расширение jQuery нужно перенести к коду слайдера, и вообще более явно отделить демо-страницу и исходники плагина

![image](https://user-images.githubusercontent.com/43137324/122875080-7804a180-d33c-11eb-9694-340edfb19aad.png)

**Comment by n0sfer666** [comment]
> Тогда const slider можно убрать, а расширение jQuery нужно перенести к коду слайдера, и вообще более явно отделить демо-страницу и исходники плагина
> 

Сделал так: abe183f, c7c8cc2, c9956f0

**Comment by Everrest1** [comment]
Одной из хороших практик jQuery плагинов является инициализация с помощью передачи параметров в `data-`атрибутах и поддержание в них актуального состояния

**Comment by n0sfer666** [comment]
> Одной из хороших практик jQuery плагинов является инициализация с помощью передачи параметров в `data-`атрибутах и поддержание в них актуального состояния

Сделал так: af1a87b
Сделал механизм при котором range и start можно задавать по разному (главное чтобы была запятая, разделяющая значения)

**Comment by Everrest1** [comment]
Проще и удобнее будет добавить возможность обновления параметров у уже инициализированного инстанса плагина

![image](https://user-images.githubusercontent.com/43137324/125313430-e508c700-e33d-11eb-9d3a-64635aa59d26.png)

**Comment by Everrest1** [comment]
Должен быть метод получения параметров слайдера в данный момент времени

![image](https://user-images.githubusercontent.com/43137324/125315752-17b3bf00-e340-11eb-9a1f-66030d1b8757.png)

**Comment by Everrest1** [comment]
data-атрибуты должны обновляться с изменением параметров слайдера

**Comment by n0sfer666** [comment]
> Проще и удобнее будет добавить возможность обновления параметров у уже инициализированного инстанса плагина
> 
> ![image](https://user-images.githubusercontent.com/43137324/125313430-e508c700-e33d-11eb-9d3a-64635aa59d26.png)

Добавил инстанс в .data('instance') 1f7186f
Вернул в основной класс метод RebuildSlider(config) 21965a5

> Должен быть метод получения параметров слайдера в данный момент времени
> 
> ![image](https://user-images.githubusercontent.com/43137324/125315752-17b3bf00-e340-11eb-9a1f-66030d1b8757.png)

Сделал тоже, что и с инстансом 1f7186f

> data-атрибуты должны обновляться с изменением параметров слайдера

Добавил в rebuildSlider(config) в этом 1c85e0b коммите

Ну и исправил все зависимости e62bd9f 1c85e0b db30b55

**Comment by Everrest1** [comment]
Как должно выглядеть взаимодействие с плагином
Метод, расширяющий jQuery должен всегда возвращать jQuery объект, чтобы продолжить цепочку вызовов, например, при инициализации он возвращает с текущим элементом jQuery<Element>
`$('.slider').sliderPlugin({ start: 10, isVertical: true }).each(...).find(...).sliderPlugin('update', { start: 21, end: 22 })`

Получать значения нужно тем же методом, например `$('.slider').sliderPlugin('getOptions')` на что должен быть получен JQuery<Object> с объектами текущих значений слайдера `{ start: 20, end: 80, isVertical: true... и т.д. }`

Обновление не должно провоцировать полное пересоздание инстанса слайдера, например, если понадобится программно изменить одно из значений
`$('.slider').sliderPlugin('update', { start: 21, end: 22 }).sliderPlugin('update', { start: 22, end: 23 })` 

Невалидные значения должны валидироваться внутри модели и не ломать слайдер

**Comment by n0sfer666** [comment]
> Как должно выглядеть взаимодействие с плагином
> Метод, расширяющий jQuery должен всегда возвращать jQuery объект, чтобы продолжить цепочку вызовов, например, при инициализации он возвращает с текущим элементом jQuery
> `$('.slider').sliderPlugin({ start: 10, isVertical: true }).each(...).find(...).sliderPlugin('update', { start: 21, end: 22 })`
> 
> Получать значения нужно тем же методом, например `$('.slider').sliderPlugin('getOptions')` на что должен быть получен JQuery с объектами текущих значений слайдера `{ start: 20, end: 80, isVertical: true... и т.д. }`
> 
> Обновление не должно провоцировать полное пересоздание инстанса слайдера, например, если понадобится программно изменить одно из значений
> `$('.slider').sliderPlugin('update', { start: 21, end: 22 }).sliderPlugin('update', { start: 22, end: 23 })`
> 
> Невалидные значения должны валидироваться внутри модели и не ломать слайдер

Закончил

**Comment by Everrest1** [comment]
Есть проблема, эти методы имеют не уникальные имена и они могут пересекаться с другими плагинами. И странно выглядит, что get метод не возвращает данные, а записывает куда-то

![image](https://user-images.githubusercontent.com/43137324/130923081-7474c7c2-39fc-46cd-99a6-e87be88c9b9c.png)

Вот у тебя есть атрибут, в котором хранится контроллер, через него можешь обмениваться данными, а в остальных методах и необходимости нет)

![image](https://user-images.githubusercontent.com/43137324/130923513-98211202-e304-4af7-99a1-702e222c0da1.png)

**Comment by n0sfer666** [comment]
> Есть проблема, эти методы имеют не уникальные имена и они могут пересекаться с другими плагинами. И странно выглядит, что get метод не возвращает данные, а записывает куда-то
> 
> Вот у тебя есть атрибут, в котором хранится контроллер, через него можешь обмениваться данными, а в остальных методах и необходимости нет)
> 
> ![image](https://user-images.githubusercontent.com/43137324/130923513-98211202-e304-4af7-99a1-702e222c0da1.png)

Исправил 
e5a9353
