### ISSUE TITLE
Кодстайл

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/FSD-Task-4-v3#4]
Этот код можно заменить простым мержем

![image](https://user-images.githubusercontent.com/43137324/116972861-5552f680-acc4-11eb-846d-fee41d279bb8.png)

**Comment by n0sfer666** [comment]
Заменил на логическое или. Я так понял это имелось ввиду.
16d90d1
```
return {
      orientation: userConfig.orientation || defaultConfig.orientation,
      start: userConfig.start || defaultConfig.start,
      range: userConfig.range || defaultConfig.range,
      step: userConfig.step || defaultConfig.step,
      connect: userConfig.connect || defaultConfig.connect,
      tooltip: userConfig.tooltip || defaultConfig.tooltip,
      scale: userConfig.scale || defaultConfig.scale,
      input: userConfig.input,
    };
```

**Comment by n0sfer666** [comment]
В полях где значения булевы, мёрж всегда возвращает true (потому что в defaultConfig лежат true).
Подкорректировал d65ba67

**Comment by Everrest1** [comment]
Тут имелось ввиду, что можно воспользоваться методом $.expand, либо spread оператором, тогда свойства перечислять не нужно

![image](https://user-images.githubusercontent.com/43137324/122875515-08db7d00-d33d-11eb-90b1-98502206c28f.png)

**Comment by n0sfer666** [comment]
> Тут имелось ввиду, что можно воспользоваться методом $.expand, либо spread оператором, тогда свойства перечислять не нужно
> 
> ![image](https://user-images.githubusercontent.com/43137324/122875515-08db7d00-d33d-11eb-90b1-98502206c28f.png)

Вот это поворот! (с)
Сделал так
```js
getCompleteConfig(defaultConfig: iCompleteConfig): iCompleteConfig {
    return <iCompleteConfig> { ...(this.userConfig || defaultConfig) };
  }
```
плюс отрефакторил немного (534a041)

**Comment by n0sfer666** [comment]
вынес получение управляющих инпутов (a5c484f)

**Comment by Everrest1** [comment]
> Вот это поворот! (с)
> Сделал так
> 
> ```js
> getCompleteConfig(defaultConfig: iCompleteConfig): iCompleteConfig {
>     return <iCompleteConfig> { ...(this.userConfig || defaultConfig) };
>   }
> ```
> 
> плюс отрефакторил немного ([534a041](https://github.com/n0sfer666/FSD-Task-4-v3/commit/534a04125c0576017797d2bd7445ecaddc48aec2))

А если передать только несколько свойств? Тогда остальные не будут инициализированы дефолтными

**Comment by n0sfer666** [comment]
> > Вот это поворот! (с)
> > Сделал так
> > ```js
> > getCompleteConfig(defaultConfig: iCompleteConfig): iCompleteConfig {
> >     return <iCompleteConfig> { ...(this.userConfig || defaultConfig) };
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > плюс отрефакторил немного ([534a041](https://github.com/n0sfer666/FSD-Task-4-v3/commit/534a04125c0576017797d2bd7445ecaddc48aec2))
> 
> А если передать только несколько свойств? Тогда остальные не будут инициализированы дефолтными

  передал пустой конфиг:
![image](https://user-images.githubusercontent.com/21785370/124377364-3f59b600-dcb4-11eb-820e-19d8b6c911f1.png)
Важный момент - это порядок. Если сделать так:
```js
getCompleteConfig(defaultConfig: iCompleteConfig): iCompleteConfig {
    return <iCompleteConfig> { ...(this.userConfig || defaultConfig) };
  }
```
то конфиг всегда будет брать значение по-умолчанию. Правильный вариант:
```js
getCompleteConfig(): iCompleteConfig {
    return <iCompleteConfig> { ...this.defaultConfig, ...this.userConfig };
  }
```
