### ISSUE TITLE
Демо-примеры

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/FSD-Task-4-v3#5]
На странице должно быть несколько примеров использования слайдера с различными начальными параметрами. Удобнее всего, если будет pug миксин для слайдера, который принимает начальные параметры, а в нём инициализировать инстанс плагина data-атрибутами

**Comment by n0sfer666** [comment]
> На странице должно быть несколько примеров использования слайдера с различными начальными параметрами. Удобнее всего, если будет pug миксин для слайдера, который принимает начальные параметры, а в нём инициализировать инстанс плагина data-атрибутами

Сделал конфигурирование через pug-mixin (91daa4c)
Добавил 2 слайдера с разными настройками (4051b6a)
