### ISSUE TITLE
Перегруженный конструктор

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/FSD-Task-4-v3#7]
> Конструктор класса должен быть максимально легковесным

https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#1.12

![image](https://user-images.githubusercontent.com/43137324/124429319-65e02580-dd76-11eb-8cad-70e7c0c94de9.png)

**Comment by n0sfer666** [comment]
Вынес получение контейнеров в отдельный метод 84bd96b

**Comment by Everrest1** [comment]
Можно всю инициализацию вынести в отдельный метод, оставить только вызов методов инициализации и передачу входных параметров внутреннему состоянию

![image](https://user-images.githubusercontent.com/43137324/124952428-e4f68780-e01c-11eb-9e8d-81c3f0e07fc3.png)

**Comment by n0sfer666** [comment]
Отрефакторил 2 конструктора (View, demo-panel) e886873

**Comment by Everrest1** [comment]
Тут получение dom-узлов тоже можно вынести в отдельный метод

![image](https://user-images.githubusercontent.com/43137324/125316379-c0621e80-e340-11eb-856d-1151df46b5ac.png)
![image](https://user-images.githubusercontent.com/43137324/125316464-cfe16780-e340-11eb-8ee3-be2a9b894e36.png)
![image](https://user-images.githubusercontent.com/43137324/125316548-e38cce00-e340-11eb-8356-13e4fe5f053f.png)
![image](https://user-images.githubusercontent.com/43137324/125316719-0e772200-e341-11eb-83cb-e9886717c4ee.png)

**Comment by n0sfer666** [comment]
> Тут получение dom-узлов тоже можно вынести в отдельный метод
> 
> ![image](https://user-images.githubusercontent.com/43137324/125316464-cfe16780-e340-11eb-8ee3-be2a9b894e36.png)

Убрал $document d8a3c5a
Переделал getElement в initElemenet 9c2950c

**Comment by n0sfer666** [comment]
> Тут получение dom-узлов тоже можно вынести в отдельный метод
> 
> ![image](https://user-images.githubusercontent.com/43137324/125316379-c0621e80-e340-11eb-856d-1151df46b5ac.png)
> ![image](https://user-images.githubusercontent.com/43137324/125316548-e38cce00-e340-11eb-8356-13e4fe5f053f.png)
> ![image](https://user-images.githubusercontent.com/43137324/125316719-0e772200-e341-11eb-83cb-e9886717c4ee.png)

Отключил strictpropertyInitialization в tsconfig 8dbc8b5
Отрефакторил 3 конструктора d8a3c5a5b7cf4c13d293e00a0b1a5ac5a58f9695 (забыл #7 написать)

**Comment by n0sfer666** [comment]
Подправил ещё 4 конструктора: Connect,Tooltip, ControlButton, DemoPanel 1977713
