### ISSUE TITLE
Именование

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/FSD-Task-4-v3#8]
> Модификатор — должен удовлетворять свойствам модификатора из английского языка. Всегда adjective или adjectival phrase
[п.4.1](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.1)

![image](https://user-images.githubusercontent.com/43137324/124949259-11f56b00-e01a-11eb-9757-a87ddd85aaee.png)

**Comment by n0sfer666** [comment]
переименовал в with-control (50feb26)

**Comment by Everrest1** [comment]
Так всё же Presenter или Controller?)

![image](https://user-images.githubusercontent.com/43137324/130923662-c19f8354-6da9-4cef-bc93-c0e03a10a453.png)

**Comment by n0sfer666** [comment]
> Так всё же Presenter или Controller?)
> 
> ![image](https://user-images.githubusercontent.com/43137324/130923662-c19f8354-6da9-4cef-bc93-c0e03a10a453.png)

А нельзя оставить как есть?
У меня material-icon стоит в VS и когда я папочку называю Controller, она красиво желтым цветом подсвечивается, но, по факту, там конечно Presenter.

**Comment by n0sfer666** [comment]
переименовал 
468b55c
