### ISSUE TITLE
Методы массивов

### ISSUE THREAD

**Issue by Everrest1** [n0sfer666/FSD-Task-4-v3#9]
Много где сейчас можно заменить заполнение нового массива вызовом map или filter, после нахождения узлов в find

![image](https://user-images.githubusercontent.com/43137324/124950539-2d14aa80-e01b-11eb-895d-556bfb9a9af3.png)

**Comment by n0sfer666** [comment]
переделал 3 геттера c4bbbea

**Comment by Everrest1** [comment]
values$ больше не jQuery объект, $ можно убрать

![image](https://user-images.githubusercontent.com/43137324/125317905-0966a280-e342-11eb-9bf4-2c4e09caca01.png)

**Comment by Everrest1** [comment]
Тут тоже можно заменить

![image](https://user-images.githubusercontent.com/43137324/125318162-4763c680-e342-11eb-8595-59d4a8c92d1e.png)
![image](https://user-images.githubusercontent.com/43137324/125318210-534f8880-e342-11eb-9ed8-7a2aea888a7c.png)
![image](https://user-images.githubusercontent.com/43137324/125318352-6f532a00-e342-11eb-87e8-176fe4fc950c.png)

Тут подумать, как переписать метод

![image](https://user-images.githubusercontent.com/43137324/125318517-94479d00-e342-11eb-90a3-0a49c2fdc5db.png)
![image](https://user-images.githubusercontent.com/43137324/125318947-ff916f00-e342-11eb-8533-4e3d3e38a4d5.png)

**Comment by n0sfer666** [comment]
> values$ больше не jQuery объект, $ можно убрать
> 
Исправил 27335c8


> Тут тоже можно заменить
> 
> ![image](https://user-images.githubusercontent.com/43137324/125318162-4763c680-e342-11eb-8595-59d4a8c92d1e.png)

Исправил bb38101

> ![image](https://user-images.githubusercontent.com/43137324/125318210-534f8880-e342-11eb-9ed8-7a2aea888a7c.png)

Исправил d23a96e

**Comment by n0sfer666** [comment]
> Тут подумать, как переписать метод
> 
> ![image](https://user-images.githubusercontent.com/43137324/125318517-94479d00-e342-11eb-90a3-0a49c2fdc5db.png)
 Сделал так 655ce4c
```js
  setPosition(startPosition: number, endPosition: number) {
    const start: number = Math.round(startPosition * this.normalizingCoefficient);
    const end: number = Math.round(endPosition * this.normalizingCoefficient);
    this.$element.css(this.orientation === 'horizontal' ? 'width' : 'height', `${end - start}%`);
    if (!this.isSinglePointer) {
      this.$element.css(this.orientation === 'horizontal' ? 'left' : 'top', `${start}%`);
    }
    this.position = [startPosition, endPosition];
  }
```

**Comment by n0sfer666** [comment]
> Тут подумать, как переписать метод
> 
> ![image](https://user-images.githubusercontent.com/43137324/125318947-ff916f00-e342-11eb-8533-4e3d3e38a4d5.png)

Убрал getPosition вообще 7b1503b
При взаимодействии пользователя со шкалой, изменения в слайдере происходит путём передачи значения а не позиции.

**Comment by Everrest1** [comment]
У тебя свойство emptyPipsNumber = 1, и т.к. оно readonly, то не будет изменено в ходе выполнения программы, зачем заполнять циклом массив, который всегда будет состоять из одного элемента?)

![image](https://user-images.githubusercontent.com/43137324/126458332-d3edd929-29b3-4ce3-a9ce-a21357953639.png)
![image](https://user-images.githubusercontent.com/43137324/126458268-a0086512-da5f-4e4d-ab45-e06a99825c0d.png)

**Comment by Everrest1** [comment]
Здесь тоже известно количество элементов в массиве, оно всегда будет равно 5, то ты можешь инициализировать массив с 5 элементами `new Array(this.valuePipsNumber).fill(0).map(...)`, а затем мапнуть их и присвоить необходимые значения

![image](https://user-images.githubusercontent.com/43137324/126459187-2e55d65d-abb2-42fc-817e-a80cb81df8a3.png)

**Comment by n0sfer666** [comment]
> Здесь тоже известно количество элементов в массиве, оно всегда будет равно 5, то ты можешь инициализировать массив с 5 элементами `new Array(this.valuePipsNumber).fill(0).map(...)`, а затем мапнуть их и присвоить необходимые значения
> 
Сделал так ddec4de
```js
  getValues(): number[] {
    const difference: number = Math.round(this.diapason / (this.valuePipsNumber - 1));
    return new Array(this.valuePipsNumber).fill(this.range[0]).map((value, index) => {
      const newVal = value + difference * index;
      return newVal <= this.range[1] ? newVal : this.range[1];
    });
  }
```

**Comment by Everrest1** [comment]
> У тебя свойство emptyPipsNumber = 1, и т.к. оно readonly, то не будет изменено в ходе выполнения программы, зачем заполнять циклом массив, который всегда будет состоять из одного элемента?)
> 
> ![image](https://user-images.githubusercontent.com/43137324/126458332-d3edd929-29b3-4ce3-a9ce-a21357953639.png)
> ![image](https://user-images.githubusercontent.com/43137324/126458268-a0086512-da5f-4e4d-ab45-e06a99825c0d.png)

А тут? Нам точно нужен массив, который будет всегда состоять из 1 элемента?

![image](https://user-images.githubusercontent.com/43137324/131085864-0e9296f3-3f1d-4033-b2a8-657e2ec5509e.png)

**Comment by n0sfer666** [comment]
> > У тебя свойство emptyPipsNumber = 1, и т.к. оно readonly, то не будет изменено в ходе выполнения программы, зачем заполнять циклом массив, который всегда будет состоять из одного элемента?)
> 
> А тут? Нам точно нужен массив, который будет всегда состоять из 1 элемента?
> 

Дело в том, что это нужно на случай если пустых пипов понадобиться больше.
На всякий случай заменил на 2, чтобы не смущало :) (000a9f3)

**Comment by Everrest1** [comment]
Я бы воспользовался методом find и после чего просто `return textInputBlocks.find(условие)?.inputs[1]`

![image](https://user-images.githubusercontent.com/43137324/131360645-e240a4a9-0b6f-4dc5-b8c9-f8162d102c5f.png)

**Comment by n0sfer666** [comment]
сделал так (b6de67b):
```js
  getSecondStart(): JQuery {
    return this.textInputBlocks.find((block) => block.configurationName === 'start')?.inputs[1]!;
  }
```

**Comment by Everrest1** [comment]
> сделал так ([b6de67b](https://github.com/n0sfer666/FSD-Task-4-v3/commit/b6de67b79e555206747bbe8380b275090d68f33b)):
> 
> ```js
>   getSecondStart(): JQuery {
>     return this.textInputBlocks.find((block) => block.configurationName === 'start')?.inputs[1]!;
>   }
> ```

А зачем тут non-null assertion? У тебя ведь может не быть этого элемента. Second start это ведь начальное значение для второго бегунка?

**Comment by n0sfer666** [comment]
> > сделал так ([b6de67b](https://github.com/n0sfer666/FSD-Task-4-v3/commit/b6de67b79e555206747bbe8380b275090d68f33b)):
> > ```js
> >   getSecondStart(): JQuery {
> >     return this.textInputBlocks.find((block) => block.configurationName === 'start')?.inputs[1]!;
> >   }
> > ```
> 
> А зачем тут non-null assertion? У тебя ведь может не быть этого элемента. Second start это ведь начальное значение для второго бегунка?

Переименовал в secondValue (Может имеет смысл переименовать в secondPointerValue?)
```js
return this.textInputBlocks.find((block) => block.configurationName === 'values')?.inputs[1]!;
```
заменил на
```js
const values = this.textInputBlocks.find((block) => block.configurationName === 'values')?.inputs;
return values ? values[values.length - 1] : $(document.createElement('input'));
```
Дело в том, что этот второй интуп там точно будет, потому что миксин text-input-block его создаёт для values и range

**Comment by Everrest1** [comment]
> Дело в том, что этот второй интуп там точно будет, потому что миксин text-input-block его создаёт для values и range

Ага, ты его скрываешь, если не используется. Тогда может добавить его в вёрстку без условий?)

![image](https://user-images.githubusercontent.com/43137324/133039148-581a8c53-065d-403b-a2be-0b7a149f2d16.png)

**Comment by n0sfer666** [comment]
> > Дело в том, что этот второй интуп там точно будет, потому что миксин text-input-block его создаёт для values и range
> 
> Ага, ты его скрываешь, если не используется. Тогда может добавить его в вёрстку без условий?)
> 
> ![image](https://user-images.githubusercontent.com/43137324/133039148-581a8c53-065d-403b-a2be-0b7a149f2d16.png)

Можно, но что делать с полем step? Там всегда одно поле. Зачем второе создавать и скрывать?
Однако, я немножко переделал (3931277)
```js
if (isNotStep)
      input(type = 'text', class = `${className}__input  js-${className}__input`, name = name, data-index = 1)
```
